{% set version = "2.0.2" %}

package:
  name: xlrd
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xlrd/xlrd-{{ version }}.tar.gz
  sha256: 08b5e25de58f21ce71dc7db3b3b8106c1fa776f3024c54e45b45b374e89234c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  files:
    - test.xls

about:
  home: https://www.python-excel.org/
  license: BSD-3-Clause AND BSD-Advertising-Acknowledgement
  license_family: BSD
  license_file: LICENSE
  summary: Library for developers to extract data from Microsoft Excel (tm) spreadsheet files
  doc_url: https://xlrd.readthedocs.io/en/latest/
  dev_url: https://github.com/python-excel/xlrd/
  description: |
    xlrd is a library for reading data and formatting information from Excel files,
    whether they are .xls or .xlsx files.



extra:
  recipe-maintainers:
    - cokelaer
