travis:
  secure:
    BINSTAR_TOKEN: MHwh5Jwl9EYPrODvpZG2nBaj+W+klqudR+NvbVXPyaimeAn81Ra7AzK2gbL1QDJSeIqdZ2qUHTDRn2iSOVHQJ8EZISttRQ1GTflLLydEvOkDvMF1aUHdzJuczQWG7Q9yw1trS/ADdJ2ZlTpDAJupsD62kCubNfrirfN4V3f0KeDoWrKb/GdYVwadyWvZ2BpBc7jjy6YiStHrhsxl6bI/ivesre46NVjiUk4dTr1FjbCaIMZizER9cdV2O6C4m+HEzkL8V457EGtgwRt43IoAasQPUqBVr8k8Z/Y98howmkbp03+NSOeMeqimAm64emftjmeRofqUSzxM/1YZWiUt6MZ3jfHW6uOk4ZvrPTeMI4tN+fkkh3xu6CuLx7lI40x+IKv3IXNg4FV+qLwR7+MPj1mWSdpQ4/5FBDe2cpb0TcSPY9nvUODlgwknzAKinrXC1GDJBVlulGpNf+47fufPeSEc9r84p1khF98CACUCHbjWf1mKVk+232zzrBwmMKai/auvF3HFL6DcIDIfPGan+ivW16dnPu8/6OkdgAcD4pNqEHuKZfe+fP9OYsVmZHzjAC+VmLkU/LdxGhZfguRyPHTN44l1teuG9GEE5dQJOmzOOCYnJTcE2qbO5y0tw5urDBqQUyNg7mdvc9S9t7Gyxrv+Ffj0+0yw0K8EDPowWEE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
