travis:
  secure:
    BINSTAR_TOKEN: eo+nU8mMianuHCFQr5GJ/sjkwW0j3bmtVJ3vQRDu8CrnQAWfFd0sLEzpSvMRXVIAR8Dq9JFEomB3vCM3Exr2uX/JmIKydv7NpXRzbdgihfA4jVRCTud3YesqVxlr7LXxd/CJS3Cfc2PghkZh7h/sFbH6AsmpgLhrw7mMSVfQ4t/nE7sm1l9ECvBFavjzDfdaW7Le+PmAlX1KcafPcc/ksUCDz6X0RHEBKc/JK9YPXhYgVGb43rdOH2gDW++7gepC7erFCA33/CWLfcsNDcB7Y2sTAb521UOolGRt9C/hOK6JlwfnnHU3HFTVUKfnpfDc9oc9cmsti8oG6Ew8RGc6mdSUUMPuaJPfy3ZLGYggZyTOLl+fM6ALLHu2nQsB86cpibjxng79cj/EuCI3WiqvUajeiHIGjRJYNrh2FcORVS0nVXRivjlN0c1bRkdEq7iaRy0Lcuj+hKqq7ZQ+DilmBkT/8czRoMHkci/VPcRYuZEyYLEuPK/U3J8gm3Q8xMmyBn+ldlZstZOAeX4KNGA4A02fqcvToTY6YLeMn7UPvAwWw1OmwSVrUUd/uqvGdyh9oubNOlr7V5sTJ8bJ7kUv8gh5N7AXRif7WdunL1+PPyjhzrFScZI4R9Fg1dqDf6g2B79zpBH4a+hHQsh5GB029W4MAFRxogCczvM73EzAeGs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
