travis:
  secure:
    BINSTAR_TOKEN: JiEvc9O+9lMZ1EUaois4rSNOqbsqoN33GXhmI1OceTqEyR3U9Ta0KrhCQYeDXZCVLZIvJy0cUCHeXPVH+siwpvGHlAg47mxpAyRHoRHg/aOGUGznLIGz384unqOWP0s5BmWqkLGSfZSJ1G8kLejkdu4jhxSPhzjOTlkSMoSgaRvLu8Gs6SegU8xbtox+FE58qHk3tBo90kOf1iRvuaPWxhP887mWHku9/sIPktiWM7MEh5bNBaiAdAsP1RrEVPXVdT5f1xn4SLarNBYLQ1A/1YC3KEo+qJdJ0/LC4mexSIo9qBYFX+/N5wadpnUCYanbpZmiMO3qbjoXA1m3qaiS6KWqTXvyjp/p6xFzzPW7wZ9YpS1aiYjzOWSA8CqJcDoeBT5IyzaLW276/+L+WfRGSONB3KFExrVmpCOCa+NEQnQt8JziEI4P0Pt5yNVGrmEHrapqwzGFsDU/I0voyQVRzyZWY05kNsYQuZw4mKY4HQhxspgwjLM85CGai5nr32TjgHgwkHKwvMjdPYngFz/lqPq0rL3ZFbv6OKY9cd6Qyx7MaRDOCoUHx/y83EfdWMhaKZL2w6u2AVAuRfagWzNBLPmIgPHJuTzKObErrbelugRInrS263bJpsPElgQ+x9Vrv82sf+NEgilzpJyqjEp4UoebJVCTcSD9XqVlFQgMuJU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
